Repository go-task/task, pull requests merged in 2019-11, with the labels that each got.

#249 Bash autocompletion for task
  completion/bash/task.bash
Labels: enhancement

#261 fix typo in usage.md
  docs/usage.md
Labels: documentation

#266 Add flag to allow tasks provided on the command line to be run in parallel
  cmd/task/task.go
  task.go
Labels: feature
