Repository go-task/task, pull requests merged in 2022-01, with the labels that each got.

#579 Avoid directory not found error in evaluating dynamic variables with newly created directory #481
  internal/execext/exec.go
  task_test.go
  testdata/dir/dynamic_var_on_created_dir/Taskfile.yml
Labels: bug

#648 docs: add nix as an installation method
  docs/installation.md
  docs/releasing_task.md
Labels: documentation, releasing

#657 Update 'community.md' to add IntelliJ plugin link
  docs/community.md
Labels: releasing

#652 Add completions to nfpms packages
  .goreleaser.yml
Labels: releasing
