Repository go-task/task, pull requests merged in 2022-06, with the labels that each got.

#767 Add Fedora Linux to installation
  docs/docs/installation.md
Labels: releasing

#755 Add --exit-code (-x) flag to enable carrying error codes from task cmds
  cmd/task/task.go
  errors.go
  task.go
  task_test.go
  testdata/error_code/Taskfile.yml
  watch.go
Labels: enhancement

#769 Fix behavior of interrupt (SIGINT, SIGTERM) signals
  .gitignore
  CHANGELOG.md
  Taskfile.yml
  bin/.keep
  cmd/sleepit/sleepit.go
  cmd/task/task.go
  internal/execext/exec.go
  signals.go
  unix_test.go
Labels: bug

#777 Add `-n` as short cut for `--dry` - solves #776
  cmd/task/task.go
  docs/docs/api_reference.md
Labels: enhancement

#783 Fix GHA grouping examples
  docs/docs/usage.md
Labels: documentation

#791 Correct `method: timestamp` example block in usage docs
  docs/docs/usage.md
Labels: documentation
