Repository go-task/task, pull requests merged in 2022-10, with the labels that each got.

#881 Clearify that sources/generate and status can be used together
  docs/docs/usage.md
Labels: documentation

#877 Fix task names for `--list` and `--list-all`
  help.go
  task_test.go
Labels: bug

#874 Colorize --list, --list-all and --summary output
  CHANGELOG.md
  help.go
  internal/logger/logger.go
  internal/summary/summary.go
Labels: enhancement

#865 Configurable watch interval #813
  cmd/task/task.go
  task.go
  task_test.go
  taskfile/taskfile.go
  testdata/watcher_interval/.gitignore
  testdata/watcher_interval/Taskfile.yaml
  watch.go
Labels: feature

#897 Improved fish shell completions
  .editorconfig
  completion/fish/task.fish
Labels: completion

#879 Aliases
  CHANGELOG.md
  Taskfile.yml
  docs/Taskfile.yml
  docs/docs/api_reference.md
  docs/docs/usage.md
  errors.go
  go.mod
  go.sum
  help.go
  internal/summary/summary.go
  task.go
  task_test.go
  taskfile/copy.go
  taskfile/included_taskfile.go
  taskfile/merge.go
  taskfile/read/taskfile.go
  taskfile/slice.go
  taskfile/task.go
  taskfile/var.go
  testdata/alias/Taskfile.yml
  testdata/alias/Taskfile2.yml
  testdata/alias/alias-duplicate.txt
  testdata/alias/alias-summary.txt
  testdata/alias/alias.txt
  variables.go
Labels: feature

#887 Add file path to YAML error message
  task_test.go
  taskfile/read/taskfile.go
  testdata/includes_incorrect/Taskfile.yml
  testdata/includes_incorrect/incomplete.yml
Labels: enhancement

#880 Suggest the most similar task name when a given task does not exist
  CHANGELOG.md
  errors.go
  go.mod
  go.sum
  help.go
  setup.go
  task.go
Labels: feature

#906 Document completion installation
  docs/docs/installation.md
Labels: documentation

#902 make powershell completion works to fill task name
  completion/ps/task.ps1
Labels: completion

#910 Bring schema in house
  docs/docs/api_reference.md
  docs/schema.json
Labels: json-schema

#895 fix: add armv5 & armv7 builds
  docs/static/install.sh
  install-task.sh
Labels: releasing
