Repository go-task/task, pull requests merged in 2022-12, with the labels that each got.

#943 fix: interpolate includes taskfile and dir
  task_test.go
  taskfile/read/taskfile.go
  testdata/includes_interpolation/Taskfile.yml
  testdata/includes_interpolation/included/Taskfile.yml
Labels: enhancement

#904 feat: add task-level dotenv support
  CHANGELOG.md
  docs/docs/api_reference.md
  docs/docs/usage.md
  docs/static/schema.json
  task_test.go
  taskfile/task.go
  testdata/dotenv_task/default/.env
  testdata/dotenv_task/default/.gitignore
  testdata/dotenv_task/default/Taskfile.yml
  variables.go
Labels: env, reviewed :heavy_check_mark:

#920 Run Taskfiles from sub/child directories
  CHANGELOG.md
  docs/docs/api_reference.md
  docs/docs/usage.md
  internal/compiler/v3/compiler_v3.go
  internal/sysinfo/uid.go
  internal/sysinfo/uid_win.go
  setup.go
  task_test.go
  taskfile/read/taskfile.go
  testdata/taskfile_walk/Taskfile.yml
  testdata/taskfile_walk/foo/bar/.gitkeep
  testdata/user_working_dir/Taskfile.yml
Labels: reviewed :heavy_check_mark:

#964 Close Taskfile after reading it
  taskfile/read/taskfile.go
Labels: bug

#970 fix: watch interval
  CHANGELOG.md
  cmd/task/task.go
  task.go
  taskfile/taskfile.go
  watch.go
Labels: bug

#971 fix: add missing nil check
  CHANGELOG.md
  taskfile/merge.go
Labels: bug
