Repository go-task/task, pull requests merged in 2023-05, with the labels that each got.

#1151 fix: tabwriter in usage output
  help.go
Labels: bug

#1144 Fix duplicate error message
  cmd/task/task.go
Labels: bug

#1143 docs: fix broken links and paths
  docs/docs/community.md
  docs/docs/integrations.md
Labels: documentation

#1183 style(website): improve language lable
  docs/docusaurus.config.js
Labels: translation
