Repository go-task/task, pull requests merged in 2023-03, with the labels that each got.

#1022 Feature 664 group error only
  cmd/task/task.go
  docs/docs/api_reference.md
  docs/docs/usage.md
  docs/static/schema.json
  internal/output/group.go
  internal/output/interleaved.go
  internal/output/output.go
  internal/output/output_test.go
  internal/output/prefixed.go
  task.go
  task_test.go
  taskfile/output.go
  testdata/output_group_error_only/Taskfile.yml
Labels: reviewed :white_check_mark:

#1029 Add `--global` (`-g`) flag
  CHANGELOG.md
  cmd/task/task.go
  docs/docs/api_reference.md
  docs/docs/usage.md
Labels: proposal

#1052 Document mk tool support
  docs/docs/community.md
Labels: documentation

#1062 feat: update the default configuration file name suffix
  CHANGELOG.md
  cmd/task/task.go
  completion/zsh/_task
  docs/docs/api_reference.md
  init.go
  task_test.go
Labels: reviewed :white_check_mark:

#1074 docs: optimize document structure
  docs/docs/api_reference.md
Labels: documentation

#1072 fix: deep copying pointers inside slices
  CHANGELOG.md
  taskfile/cmd.go
  taskfile/copy.go
  taskfile/dep.go
  taskfile/platforms.go
  taskfile/precondition.go
  taskfile/task.go
Labels: refactoring

#1096 feat: release tool improvements
  CHANGELOG.md
  Taskfile.yml
  cmd/release/main.go
Labels: releasing

#1091 docs: optimize document style
  docs/docs/intro.md
Labels: documentation

#1098 Ignore .hg for Mercurial, too
  watch.go
Labels: watch

#1090 docs: add winget installation instructions
  docs/docs/installation.md
Labels: documentation, releasing
