Repository go-task/task, pull requests merged in 2023-08, with the labels that each got.

#1290 docs: add required version for supporting loops
  docs/docs/usage.md
Labels: area: docs

#1309 fix: make sure USER_WORKING_DIR works corrently with includes
  CHANGELOG.md
  internal/filepathext/filepathext.go
  setup.go
  task.go
  task_test.go
  taskfile/included_taskfile.go
  testdata/user_working_dir_with_includes/Taskfile.yml
  testdata/user_working_dir_with_includes/included/Taskfile.yml
  testdata/user_working_dir_with_includes/somedir/.keep
Labels: area: variables

#1313 fix: `--status` flag should not have side-effects
  CHANGELOG.md
  cmd/task/task.go
Labels: type: bug
