Repository go-task/task, pull requests merged in 2023-06, with the labels that each got.

#1163 feat(prompts): add ability for tasks to prompt user pre execution
  cmd/task/task.go
  docs/docs/api_reference.md
  docs/docs/usage.md
  docs/static/schema.json
  errors/errors.go
  errors/errors_task.go
  task.go
  task_test.go
  taskfile/task.go
  testdata/prompt/Taskfile.yml
  variables.go
Labels: state: reviewed :white_check_mark:

#1211 Better docs for `--sort`
  cmd/task/task.go
  docs/docs/api_reference.md
Labels: area: docs

#1201 chore(website): update website colors
  docs/src/css/custom.css
Labels: area: docs

#1214 Support for experiment env vars
  docs/docs/experiments/experiments.md
  internal/experiments/experiments.go
Labels: state: reviewed

#1216 feat: implement gentle force experiment draft
  CHANGELOG.md
  args/args.go
  args/args_test.go
  cmd/task/task.go
  docs/docs/experiments/experiments.md
  internal/experiments/experiments.go
  task.go
  task_test.go
  taskfile/call.go
  testdata/force/Taskfile.yml
Labels: state: reviewed

#1204 A way to enforce required variables
  docs/docs/api_reference.md
  docs/docs/usage.md
  docs/static/schema.json
  errors/errors.go
  errors/errors_task.go
  requires.go
  task.go
  taskfile/requires.go
  taskfile/task.go
  variables.go
Labels: type: feature, area: variables

#1245 fix: ignore all errors when reading dotenv for experiments
  internal/experiments/experiments.go
Labels: type: bug
