Repository go-task/task, pull requests merged in 2023-09, with the labels that each got.

#1315 chore: update experiments and deprecation docs
  docs/docs/changelog.md
  docs/docs/community.md
  docs/docs/deprecations/deprecations.md
  docs/docs/deprecations/template.md
  docs/docs/deprecations/version_2_schema.md
  docs/docs/donate.md
  docs/docs/experiments/experiments.md
  docs/docs/experiments/gentle_force.md
  docs/docs/experiments/template.md
  docs/docs/experiments/workflow.md
  docs/docs/faq.md
  docs/docs/integrations.md
  docs/docs/styleguide.md
  docs/docs/taskfile_versions.md
Labels: area: docs

#1152 feat: remote taskfiles (HTTP)
  CHANGELOG.md
  args/args.go
  args/args_test.go
  cmd/task/task.go
  docs/docs/experiments/remote_taskfiles.md
  errors/errors.go
  errors/errors_taskfile.go
  internal/experiments/experiments.go
  internal/logger/logger.go
  setup.go
  task.go
  task_test.go
  taskfile/included_taskfile.go
  taskfile/read/cache.go
  taskfile/read/node.go
  taskfile/read/node_base.go
  taskfile/read/node_file.go
  taskfile/read/node_http.go
  taskfile/read/taskfile.go
Labels: state: wip, proposal

#1325 checksum: Use XXH3 algorithm instead of md5
  docs/docs/taskfile_versions.md
  docs/i18n/es-ES/docusaurus-plugin-content-docs/current/taskfile_versions.md
  docs/i18n/fr-FR/docusaurus-plugin-content-docs/current/taskfile_versions.md
  docs/i18n/ja-JP/docusaurus-plugin-content-docs/current/taskfile_versions.md
  docs/i18n/pt-BR/docusaurus-plugin-content-docs/current/taskfile_versions.md
  docs/i18n/ru-RU/docusaurus-plugin-content-docs/current/taskfile_versions.md
  docs/i18n/tr-TR/docusaurus-plugin-content-docs/current/taskfile_versions.md
  docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/taskfile_versions.md
  go.mod
  go.sum
  internal/fingerprint/sources_checksum.go
  task_test.go
Labels: type: performance

#1329 chore(deps): upgrade slim-sprig to v3.0.0
  go.mod
  go.sum
  internal/templater/funcs.go
Labels: area: dependencies
