Repository go-task/task, pull requests merged in 2023-04, with the labels that each got.

#1101 chore: fix auto upload workflow
  .github/workflows/upload-source-documents.yml
Labels: translation

#1104 docs: fix usage.md
  docs/docs/usage.md
Labels: documentation

#1105 feat: implement task sorting with `--sort` flag
  CHANGELOG.md
  args/args_test.go
  cmd/task/task.go
  docs/docs/api_reference.md
  help.go
  internal/deepcopy/deepcopy.go
  internal/orderedmap/orderedmap.go
  internal/orderedmap/orderedmap_test.go
  internal/output/output_test.go
  internal/sort/sorter.go
  internal/sort/sorter_test.go
  internal/summary/summary.go
  internal/summary/summary_test.go
  setup.go
  task.go
  task_test.go
  taskfile/cmd.go
  taskfile/merge.go
  taskfile/read/dotenv.go
  taskfile/read/taskfile.go
  taskfile/task.go
  taskfile/taskfile_test.go
  taskfile/tasks.go
  taskfile/var.go
  variables.go
Labels: reviewed :white_check_mark:

#1114 feat: custom error codes
  CHANGELOG.md
  cmd/task/task.go
  docs/docs/api_reference.md
  errors.go
  errors/errors.go
  errors/errors_task.go
  errors/errors_taskfile.go
  init.go
  task.go
  task_test.go
  taskfile/read/taskfile.go
  watch.go
Labels: enhancement

#1118 feat: use mockery/testify for mocking instead of mockgen/gomock
  .mockery.yaml
  Taskfile.yml
  go.mod
  go.sum
  internal/fingerprint/checker_mock.go
  internal/fingerprint/task_test.go
  internal/mocks/sources_checkable.go
  internal/mocks/status_checkable.go
Labels: refactoring

#1137 refactor: remove newlines from formatter print functions
  cmd/task/task.go
  help.go
  internal/compiler/v2/compiler_v2.go
  internal/compiler/v3/compiler_v3.go
  internal/fingerprint/status.go
  internal/logger/logger.go
  internal/summary/summary.go
  precondition.go
  signals.go
  task.go
  watch.go
Labels: refactoring

#1134 Fix for swallowing unkown errors - fixes #1133
  cmd/task/task.go
Labels: bug
