Repository go-task/task, pull requests merged in 2024-08, with the labels that each got.

#1762 feat(defer): expose `EXIT_CODE` special variable to `defer:`
  CHANGELOG.md
  internal/execext/exec.go
  task.go
  task_test.go
  testdata/exit_code/Taskfile.yml
  variables.go
  website/docs/reference/templating.mdx
  website/docs/usage.mdx
Labels: type: enhancement

#1764 feat: add ALIAS special var
  internal/compiler/compiler.go
  testdata/special_vars/Taskfile.yml
  testdata/special_vars/included/Taskfile.yml
  website/docs/reference/templating.mdx
Labels: area: variables, experiment: candidate

#1754 docs: fix variable name
  website/docs/usage.mdx
Labels: area: docs

#1715 fix(remote): TASK_REMOTE_DIR does not work when absolute
  setup.go
Labels: type: bug, area: remote
