Repository go-task/task, pull requests merged in 2024-04, with the labels that each got.

#1577 chore(website): upgrade docusaurus
  website/Taskfile.yml
  website/package.json
  website/yarn.lock
Labels: area: dependencies, javascript

#1583 chore(crowdin): fixes to `crowdin.yml`
  website/crowdin.yml
Labels: area: docs

#1584 fix: fix bug for files with special chars `&()`
  CHANGELOG.md
  internal/execext/exec.go
Labels: type: bug

#1617 chore(website): disable translations for now
  website/docusaurus.config.ts
Labels: area: docs, area: translation

#1613 Support tilde home directory auto completion and spaces in directories
  completion/zsh/_task
Labels: area: completions

#1628 Fix reference to GOOS and GOARCH link
  website/docs/api_reference.mdx
  website/versioned_docs/version-latest/api_reference.mdx
Labels: area: docs
