Repository go-task/task, pull requests merged in 2024-09, with the labels that each got.

#1157 feat: completions command
  cmd/task/task.go
  completion.go
  internal/flags/flags.go
  website/docs/deprecations/completion_scripts.mdx
  website/docs/installation.mdx
Labels: area: completions

#1713 refactor: check if the remote exists just before reading it
  taskfile/node_http.go
  taskfile/reader.go
  taskfile/taskfile.go
Labels: type: refactoring, type: performance, area: remote

#1783 chore: configure Renovate
  .github/renovate.json
Labels: area: dependencies

#1792 chore(website): upgrade docusaurus to the latest version
  website/package.json
  website/yarn.lock
Labels: area: docs, area: dependencies

#1793 chore(website): disable crowdin completely
  .github/workflows/upload-source-documents.yml
  website/Taskfile.yml
  website/crowdin.yml
  website/docs/community.mdx
  website/docs/translate.mdx
  website/docusaurus.config.ts
  website/package.json
  website/src/api/crowdin.js
  website/versioned_docs/version-latest/community.mdx
  website/versioned_docs/version-latest/translate.mdx
  website/yarn.lock
Labels: area: docs, area: translation

#1811 docs: exit code zero is not an error
  website/docs/reference/cli.mdx
  website/versioned_docs/version-latest/reference/cli.mdx
Labels: area: docs

#1824 fix: snapshot builds and wrong winget version
  .goreleaser.yml
Labels: area: releasing

#1830 fix: checksum override when passed via ldflags
  internal/version/version.go
Labels: area: releasing

#1652 feat(remote): support include git remote
  go.mod
  go.sum
  taskfile/node.go
  taskfile/node_file.go
  taskfile/node_git.go
  taskfile/node_git_test.go
  taskfile/node_http.go
  taskfile/node_test.go
  website/docs/experiments/remote_taskfiles.mdx
Labels: area: remote
