Repository go-task/task, pull requests merged in 2024-05, with the labels that each got.

#1644 fix(docs): add references to experiments links
  website/docs/contributing.mdx
  website/versioned_docs/version-latest/contributing.mdx
Labels: area: docs

#1624 feat: task executable variable
  internal/compiler/compiler.go
Labels: area: variables

#1619 better yaml parsing
  cmd/task/task.go
  errors/error_taskfile_decode.go
  errors/errors.go
  errors/themes/task.xml
  go.mod
  go.sum
  task_test.go
  taskfile/ast/cmd.go
  taskfile/ast/dep.go
  taskfile/ast/for.go
  taskfile/ast/glob.go
  taskfile/ast/include.go
  taskfile/ast/output.go
  taskfile/ast/platforms.go
  taskfile/ast/platforms_test.go
  taskfile/ast/precondition.go
  taskfile/ast/task.go
  taskfile/ast/taskfile.go
  taskfile/ast/tasks.go
  taskfile/ast/var.go
  taskfile/reader.go
Labels: area: parser

#1650 chore: update actions version because node 16 is deprecated
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/upload-source-documents.yml
Labels: area: ci/cd

#1653 docs: template reference
  website/docs/deprecations/template_functions.mdx
  website/docs/reference/_category_.yml
  website/docs/reference/cli.mdx
  website/docs/reference/environment.mdx
  website/docs/reference/schema.mdx
  website/docs/reference/templating.mdx
  website/docs/usage.mdx
Labels: area: docs
