Repository go-task/task, pull requests merged in 2024-06, with the labels that each got.

#1699 chore: release riscv64 binary on Linux
  .goreleaser.yml
Labels: area: releasing

#1636 feat(remote): prefix checksums/cached files with the filename
  taskfile/cache.go
  taskfile/node.go
  taskfile/node_file.go
  taskfile/node_http.go
  taskfile/node_stdin.go
Labels: area: remote

#1639 feat(remote): add a command to clear the cache
  cmd/task/task.go
  internal/flags/flags.go
  taskfile/cache.go
  website/docs/experiments/remote_taskfiles.mdx
Labels: area: remote

#1656 fix: list-task with multiline desc
  go.mod
  go.sum
  help.go
  internal/experiments/experiments.go
  testdata/desc/Taskfile.yml
Labels: area: formatting
