Repository go-task/task, pull requests merged in 2025-03, with the labels that each got.

#2085 refactor: executor functional options
  cmd/task/task.go
  executor.go
  help.go
  internal/flags/flags.go
  setup.go
  task.go
  task_test.go
  taskfile/reader.go
  taskfile/snippet.go
  watch_test.go
Labels: area: package api

#2130 fix(fish): fish completion error due to variable shadowing
  completion/fish/task.fish
Labels: area: completions

#2048 feat(watch): migrate to fsnotify
  Taskfile.yml
  executor.go
  go.mod
  go.sum
  internal/fingerprint/glob.go
  internal/fingerprint/sources_checksum.go
  internal/fsnotifyext/fsnotify_dedup.go
  testdata/watch/.gitignore
  testdata/watch/Taskfile.yaml
  testdata/watcher_interval/Taskfile.yaml
  watch.go
  watch_test.go
  website/docs/usage.mdx
  website/static/schema.json
Labels: area: watcher
